### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by daviddeejjames** [juniordevio/splashpage#43]
Create a transparent, right-aligned navigation bar
- Meetup
- Become a speaker
- Twitter
- Slack

**Comment by RoyJia** [comment]
Hi @daviddeejjames do you have an expectation example? what does it looks like?

**Comment by daviddeejjames** [comment]
hi @RoyJia, sorry this is being setup for a Hacktoberfest event tonight in Melbourne.

**Comment by javabada** [comment]
Will do!
