### ISSUE TITLE
Find Meetup Icon (SVG)

### ISSUE THREAD

**Issue by daviddeejjames** [juniordevio/splashpage#46]
For the navigation we would like a Meetup Icon, look for free use svgs at places such as https://www.flaticon.com/

**Comment by cameocodes** [comment]
I'll do this one :)

**Comment by cameo-myob** [comment]
[See PR](https://github.com/juniordevio/splashpage/pull/62)

**Comment by daviddeejjames** [comment]
Thanks @cameo-myob @cameocodes 🍰 👍 🎉
