### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by cameo-myob** [juniordevio/splashpage#75]
## Issue
There is currently no issue template to standardize the formatting of issues. This could lead to missed/incomplete issues in the future.

## Details
See Github's article on Issue Templates [here](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/). Of note, things that could be included in an issue template include:

- Expected behavior and actual behavior.
- Steps to reproduce the problem.
- Specifications like the version of the project, operating system, or hardware.

**Comment by josh-** [comment]
Fixed in #87 - thanks for raising this!
