### ISSUE TITLE
Add Alt Tags to Images

### ISSUE THREAD

**Issue by cameo-myob** [juniordevio/splashpage#76]
## Issue
Images in nav bar currently lack alt tags.

## Details
Descriptive alt tags on images are important to increase the accessibility of the website for people using screen reader and other accessibility devices. See the [W3 recommendations](https://www.w3.org/WAI/tutorials/images/).

**Comment by dy1z** [comment]
working on it.

**Comment by daviddeejjames** [comment]
Thanks heaps @dy1z !!!
