### ISSUE TITLE
Update the 404 page

### ISSUE THREAD

**Issue by josh-** [juniordevio/splashpage#95]
Our [404 page](https://juniordev.io/404) is pretty cool, but we reckon it could be a bit cooler! Feel free too add some emoji or other emojis 😄

**Comment by pratham-10** [comment]
Please assign.

**Comment by Nitish-web-nik** [comment]
Please assign, I want to contribute in this issue.

**Comment by RabsonJ** [comment]
I would love to contribute to this issue
